# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileCopyrightText: Â© 2025 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

[tool.black]
line-length = 132
