---
# SPDX-PackageSummary: finnix-live-build
# SPDX-FileCopyrightText: Copyright (C) 2022-2024 Ryan Finnie
# SPDX-License-Identifier: CC-BY-SA-4.0

title: "LOCALE-CONFIG(1) | locale-config"
author: "Ryan Finnie <ryan@finnie.org>"
