---
# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileCopyrightText: Â© 2022 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: CC-BY-SA-4.0

title: "LOCALE-CONFIG(1) | locale-config"
author: "Ryan Finnie <ryan@finnie.org>"
